In [16]:
import pandas as pd
import numpy as np

In [17]:
students_dict = {"name" : ["karen", "jean", "moe", "kim"], "lab 1" : [3, 2.5, 2, 1.5], "lab 2" : [2.8,3.0, 2.8, 1.5], "lab 3" : [3,2.9, 2, 1.5], "test 1" : [10.0, 9.0, 6.5, None]}
students = pd.DataFrame(students_dict)
students.set_index("name", inplace = True)

In [18]:
students.describe()

          lab 1     lab 2     lab 3     test 1
count  4.000000  4.000000  4.000000   3.000000
mean   2.250000  2.525000  2.350000   8.500000
std    0.645497  0.689807  0.723418   1.802776
min    1.500000  1.500000  1.500000   6.500000
25%    1.875000  2.475000  1.875000   7.750000
50%    2.250000  2.800000  2.450000   9.000000
75%    2.625000  2.850000  2.925000   9.500000
max    3.000000  3.000000  3.000000  10.000000

In [19]:
students.columns

Index(['lab 1', 'lab 2', 'lab 3', 'test 1'], dtype='object')

In [20]:
students.head()

          lab 1  lab 2  lab 3  test 1
name
karen       3.0    2.8    3.0    10.0
jean        2.5    3.0    2.9     9.0
mohammed    2.0    2.8    2.0     6.5
kim         1.5    1.5    1.5     NaN

In [21]:
students["lab 4"] = [3.0, 2.9, 2.5, 2.0]
students.head()

          lab 1  lab 2  lab 3  test 1  lab 4
name
karen       3.0    2.8    3.0    10.0    3.0
jean        2.5    3.0    2.9     9.0    2.9
mohammed    2.0    2.8    2.0     6.5    2.5
kim         1.5    1.5    1.5     NaN    2.0

In [27]:
students.drop(columns=["lab 4"], inplace = True)
students.head()

       name  lab 1  lab 2  lab 3  test 1
0     karen    3.0    2.8    3.0    10.0
1      jean    2.5    3.0    2.9     9.0
2  mohammed    2.0    2.8    2.0     6.5
3       kim    1.5    1.5    1.5     NaN

In [22]:
students["sum labs"] = students["lab 1"] + students["lab 2"] + students["lab 3"] + students["lab 4"]

In [23]:
students.head()

          lab 1  lab 2  lab 3  test 1  lab 4  sum labs
name
karen       3.0    2.8    3.0    10.0    3.0      11.8
jean        2.5    3.0    2.9     9.0    2.9      11.3
mohammed    2.0    2.8    2.0     6.5    2.5       9.3
kim         1.5    1.5    1.5     NaN    2.0       6.5

In [24]:
students["sum labs"].corr(students["test 1"])

0.9958705948858223

In [25]:
students.at["kim", "test 1"] = 4.0
students.head()

          lab 1  lab 2  lab 3  test 1  lab 4  sum labs
name
karen       3.0    2.8    3.0    10.0    3.0      11.8
jean        2.5    3.0    2.9     9.0    2.9      11.3
mohammed    2.0    2.8    2.0     6.5    2.5       9.3
kim         1.5    1.5    1.5     4.0    2.0       6.5

In [26]:
students.sort_values(by = "test 1", ascending = True)

          lab 1  lab 2  lab 3  test 1  lab 4  sum labs
name
kim         1.5    1.5    1.5     4.0    2.0       6.5
mohammed    2.0    2.8    2.0     6.5    2.5       9.3
jean        2.5    3.0    2.9     9.0    2.9      11.3
karen       3.0    2.8    3.0    10.0    3.0      11.8